# Return debugging messages to the terminal.
debug_mode: False

# States the number of maps provided by the map_server.
maps_nr: 2

# Dicts consisting of parameters of the included maps
map1: {
  image: world1.pgm,
  resolution: 0.050000,
  origin: [-4.592538, -3.278644, 0.000000],
  negate: 0,
  occupied_thresh: 0.65,
  free_thresh: 0.196
}

map2: {
  image: sim_simple.pgm,
  resolution: 0.050000,
  origin: [-3.246519, -3.028618, 0.000000],
  negate: 0,
  occupied_thresh: 0.65,
  free_thresh: 0.196
}

# To add more maps, append the .yaml file in the same style as map1.
# The second map should be called map2, the third map3, etc.

